### ISSUE TITLE
seed file does not load

### ISSUE THREAD

**Issue by bkleinen** [imimaps/imimaps#118]
Auf Master kann die Seed-Datei nicht mehr angewendet werden: 

master / commit 8bad6f2
./docker-tool development start

- folgender Fehler: 

imimaps-development | ActiveRecord::RecordInvalid: Fehlerhafte Angaben: Password ist zu kurz
imimaps-development | /usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/validations.rb:79:in `raise_record_invalid'

imimaps-development | seeding database
imimaps-development exited with code 1

**Comment by bkleinen** [comment]
I'm going to fix that for now as I can't see my version info changes without it.

**Comment by bkleinen** [comment]
sorry, this is more than just adding a longer password:

2.4.1 :011 >   User.create(:email => "user@imimaps.de", password: "foofoofoo123123", password_confirmation: "foofoofoo123123", student_id: 1)
NoMethodError: undefined method `encrypted_password=' for #<User:0x007fb468332218>
	from /Users/kleinen/.rvm/gems/ruby-2.4.1@imi-maps-rails42-bootstrap-update/gems/activemodel-4.2.8/lib/active_model/attribute_methods.rb:433:in `method_missing'

- also, the factories are broken due to the same error. I'll briefly look into while on earth the tests did pass at all with that and allow it into master.

**Comment by bkleinen** [comment]
ok, it was that easy after all - but not easy to test it in the console as only the student_id attribute, but not the student attribute is writable on user. This is an inconsistency and should be fixed.
